In [55]:
import numpy as np

dict = {chr(i):i for i in range(1,123)}
dict['0'] = 0
user_enter = input('请输入:') 
leng = len(user_enter) // 3 if len(user_enter) % 3 == 0 else len(user_enter) // 3+1
quzheng = user_enter.zfill(leng*3)
b = [dict[i] for i in quzheng]
np_c = np.array(b)
c = np_c.reshape(leng,3)
print('加密前:')
print(c)
key = np.mat([[1,3,4],
              [1,5,7],
              [1,6,9]])
d = c*key
print('加密后:')
print(d)
print('解密后:')
jiemi = (c*key.I)*key
print(jiemi)
      



请输入:asdffgh
加密前:
[[  0   0  97]
 [115 100 102]
 [102 103 104]]
加密后:
[[  97  582  873]
 [ 317 1457 2078]
 [ 309 1445 2065]]
解密后:
[[  0.   0.  97.]
 [115. 100. 102.]
 [102. 103. 104.]]


In [23]:
a = '我是你爸爸更好的风格的高级的共和党和孤独是股份的合格的碎骨胡说的话跟谁好归宿'

In [24]:
for i in a:
    print(ord(i))

25105
26159
20320
29240
29240
26356
22909
30340
39118
26684
30340
39640
32423
30340
20849
21644
20826
21644
23396
29420
26159
32929
20221
30340
21512
26684
30340
30862
39592
32993
35828
30340
35805
36319
35841
22909
24402
23487


In [54]:
def is_chinese(uchar):
    dict = {chr(i):i for i in range(97,123)}
    for i in uchar:
        for k,v in dict.items():
            if k == i:
                print(v)
is_chinese('action')

97
99
116
105
111
110


TypeError: an integer is required (got type str)

In [56]:
ord('!')

33