In [7]:
import numpy as np
# 加密
I = np.mat([[1,3,20],
             [9,15,14]])
# 密钥
k =np.mat([[1,0,1],
             [3,2,7],
            [1,9,2]]) 
C = I *k
print(C)
# 解密



[[ 30 186  62]
 [ 68 156 142]]
------------------
[[ 70 186  62]
 [ 96 156 142]]


In [11]:
#加密密钥矩阵
K_LIST = [[17, 17, 5],
           [21, 18, 21],
           [2, 2, 19]]
 
 #26个字母列表：方便找出对应下标
ALPHABET = ["A","B","C","D","E","F","G",
             "H","I","J","K","L","M","N",
             "O","P","Q","R","S","T","U",
             "V","W","X","Y","Z"]

def get_index(alphabet):
    """
    获得字母在字母表中的对应位置(下标)
    :param alphabet: 明文字母
    :return: 下标
    """
    alphabet = alphabet.upper()
    return ALPHABET.index(alphabet)

def deal_index(list_index):
     """
     加密处理C＝KP
     :param list_index: 每一组明文字母的下标
     :return: 加密后密文的下标
     """
     deal_list = [0,0,0]
     for i in range(len(K_LIST)):
         for j in range(len(K_LIST[i])):
             deal_list[i] += list_index[j] * K_LIST[i][j]
         deal_list[i] = (deal_list[i] % 26)
     return deal_list

def get_alphabet(deal_list):
     """
     通过字母的下标获得对应字母
     :param deal_list: 下标的列表
     :return: 返回密文字母列表
     """
     cipher_list = []
     for i in deal_list:
         cipher_list.append(ALPHABET[i])
     return cipher_list

def encryption(clear_text):
     """
     加密时调用的函数
     :param clear_text:输入的明文
     :return: 加密后的密文
     """
     list_clear_text = list(clear_text.strip().replace(" ", ""))
     print(list_clear_text)
     #明文每3个一组，不足则补充字母Z
     for i in range(len(list_clear_text)):
         if i % 3 == 0 and i+2 > len(list_clear_text)-1:  # 越界，则需在最后一组不足3个补字母Z
             if i+1 > len(list_clear_text)-1:
                 list_clear_text.insert(i + 1, "Z")
             list_clear_text.insert(i + 2, "Z")
     print(list_clear_text)
     cipher_list = []   #用来存入密文
     #明文每3个为一组，找出每组在字母表中的位置(用一个列表来保存)
     for i in range(len(list_clear_text)):
         if i % 3 == 0 and i+2 <= len(list_clear_text)-1:
             x = get_index(list_clear_text[i])
             y = get_index(list_clear_text[i+1])
             z = get_index(list_clear_text[i+2])
             list_index = [x, y, z]
             print(list_index)
             #调用deal_inde函数进行加密 矩阵K与明文P运算得到密文C，即C＝KP
             deal_list = deal_index(list_index)
             #print(deal_list)    #测试用的
             part_cipher_list = get_alphabet(deal_list)   #返回一组密文
             cipher_list.extend(part_cipher_list)
             #print(part_cipher_list)      #测试用的

     print(cipher_list)
     return "".join(cipher_list)

def decryption():
     print("解密未实现...")

if __name__ == "__main__":
     while True:
         choice = input("Please input E for encryption or D for decryption:")
         if choice == "E":
             clear_text = input("请输入明文:")
             print("加密成功！密文:%s" % encryption(clear_text))
         if choice == "D":
             cipher_text = input("请输入密文:")
             decryption()

Please input E for encryption or D for decryption:action
Please input E for encryption or D for decryption:action
Please input E for encryption or D for decryption:E
请输入明文:action
['a', 'c', 't', 'i', 'o', 'n']
['a', 'c', 't', 'i', 'o', 'n']
[0, 2, 19]
[8, 14, 13]
['Z', 'T', 'B', 'X', 'R', 'F']
加密成功！密文:ZTBXRF
Please input E for encryption or D for decryption:d
Please input E for encryption or D for decryption:D
请输入密文:ZTBXRF
解密未实现...


KeyboardInterrupt: 

In [48]:
str2 = "aaabccddd"
def Zip(str2):
    zip = ""
    n = 1
    for i in range(len(str2)):
        if str2[i] == str2[i]:
            n += 1
        else:
            str2_n = str(n)
            zip += str2[i]
            if n != 1:
                zip += str2_n
            n = 1
    return zip
print(Zip(str2))

0
1
2
3
4
5
6
7
8



In [15]:
import numpy as np
# 加密
k = np.mat([[1,2,3],
            [2,2,1],
            [3,4,3]])
print(k.I)

[[ 1.   3.  -2. ]
 [-1.5 -3.   2.5]
 [ 1.   1.  -1. ]]


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
